[versions]
kotlin  = "2.3.0"
junit5  = "6.0.2"
semver  = "0.18.0"
mockito = "5.21.0"
mockitoKotlin = "6.1.0"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm",              version.ref = "kotlin" }
semver = { id = "com.github.jmongard.git-semver-plugin", version.ref = "semver" }

[libraries]
junit5Bom = { module = "org.junit:junit-bom",      version.ref = "junit5"  }
mockito   = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockitoKotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockitoKotlin" }
semver    = { module = "com.github.jmongard.git-semver-plugin:com.github.jmongard.git-semver-plugin.gradle.plugin", version.ref = "semver"}
